const actionTypes = {
    DEVICES_LOAD_START: "DEVICES_LOAD_START",
    DEVICES_LOAD_SUCCESS: "DEVICES_LOAD_SUCCESS",
    DEVICES_LOAD_ERROR: "DEVICES_LOAD_ERROR",
    DEVICE_DETAILS_LOAD_START: "DEVICE_DETAILS_LOAD_START",
    DEVICE_DETAILS_LOAD_SUCCESS: "DEVICE_DETAILS_LOAD_SUCCESS",
    DEVICE_DETAILS_LOAD_ERROR: "DEVICE_DETAILS_LOAD_ERROR",
    DEVICES_REFRESHER_CONNECT: "DEVICES_REFRESHER_CONNECT",
    DEVICES_REFRESHER_UPDATE: "DEVICES_REFRESHER_UPDATE",
    DEVICES_REFRESHER_ERROR: "DEVICES_REFRESHER_ERROR"
}
export default actionTypes;